language: python
python:
  - "2.7"
  - "pypy"

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt

# environment dependencies
before_script:
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.27.zip
  - unzip -q google_appengine_1.9.27.zip
  - ln -s google_appengine/google google

# command to run tests
script:
  - python setup.py test
